export const courseData = [
  {
    id: 1,
    src: "/course-img-1.png",
    title: "Learn Figma from Basic",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Music",
  },
  {
    id: 2,
    src: "/course-img-2.png",
    title: "Build Digital Asset",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Drawing & Painting",
  },
  {
    id: 3,
    src: "/course-img-3.png",
    title: "the Power of Big Data",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Marketing",
  },
  {
    id: 4,
    src: "/course-img-4.png",
    title: "Balancing Productivity",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Animation",
  },
  {
    id: 5,
    src: "/course-img-5.png",
    title: "Mastering Money",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Social Media",
  },
  {
    id: 6,
    src: "/course-img-6.png",
    title: "From Idea to Startup",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "UI/UX Design",
  },
  {
    id: 7,
    src: "/course-img-1.png",
    title: "Learn Figma from Basic",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Creative Marketing",
  },
  {
    id: 8,
    src: "/course-img-2.png",
    title: "Build Digital Asset",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Cooking",
  },
  {
    id: 9,
    src: "/course-img-3.png",
    title: "the Power of Big Data",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Cooking",
  },
  {
    id: 10,
    src: "/course-img-4.png",
    title: "Balancing Productivity",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Creative Marketing",
  },
  {
    id: 11,
    src: "/course-img-5.png",
    title: "Mastering Money",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "UI/UX Design",
  },
  {
    id: 12,
    src: "/course-img-6.png",
    title: "From Idea to Startup",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Social Media",
  },
  {
    id: 13,
    src: "/course-img-1.png",
    title: "Learn Figma from Basic",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Animation",
  },
  {
    id: 14,
    src: "/course-img-2.png",
    title: "Build Digital Asset",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Music",
  },
  {
    id: 15,
    src: "/course-img-3.png",
    title: "the Power of Big Data",
    rating: 4.5,
    author: "purepearl studio",
    src2: "/course-img-7.png",
    price: 25,
    access: "lifetime",
    category: "Drawing & Painting",
  },
];